version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: lucky-admin-local
    ports:
      - "8000:8000"
    volumes:
      - ./data/dynamodb:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
    restart: unless-stopped
