version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: lucky-admin-api
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: lucky-admin
    ports:
      - "5432:5432"
