// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	_ "github.com/danielgtaylor/huma/v2/formats/cbor"
)

// Injectors from wire.go:

func injectAppDependencies() (Application, error) {
	appConfig := provideAppConfig()
	postgresConfig := providePostgresConfig(appConfig)
	db, err := provideDBConnection(postgresConfig)
	if err != nil {
		return nil, err
	}
	serverConfig := provideHttpServerConfig(appConfig)
	server := provideHTTPServer(serverConfig)
	application := NewApp(appConfig, db, server)
	return application, nil
}
