// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	_ "github.com/danielgtaylor/huma/v2/formats/cbor"
)

// Injectors from wire.go:

func injectAppDependencies() (Application, error) {
	appConfig := provideAppConfig()
	postgresConfig := providePostgresConfig(appConfig)
	repository, err := provideRepository(postgresConfig)
	if err != nil {
		return nil, err
	}
	serverConfig := provideHttpServerConfig(appConfig)
	gameService := provideGameService(repository)
	gameHandler := provideGameHandler(gameService)
	server := provideHTTPServer(serverConfig, gameHandler)
	application := NewApp(appConfig, repository, server)
	return application, nil
}
