// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
)

import (
	_ "github.com/danielgtaylor/huma/v2/formats/cbor"
)

// Injectors from wire.go:

func injectAppDependencies(ctx context.Context) (Application, error) {
	appConfig := provideAppConfig()
	serverConfig := provideHttpServerConfig(appConfig)
	dynamoDBConfig := provideDynamoConfig(appConfig)
	client, err := provideDynamoClient(ctx, dynamoDBConfig)
	if err != nil {
		return nil, err
	}
	repository := provideRepository(client)
	gameService := provideGameService(ctx, repository)
	gameHandler := provideGameHandler(gameService)
	server := provideHTTPServer(serverConfig, gameHandler)
	application := NewApp(appConfig, server)
	return application, nil
}
